language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

dist: trusty

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CC_TEST_REPORTER_ID=020721f46c958689dbad40b049bbff903dff55b817f959f2a6dd1ce531409f5f
#### Rest of code omitted for clarity ####
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
#### Rest of code omitted for clarity ####
after_script:
- ls -a
- ./cc-test-reporter format-coverage -t cobertura -d target/site/cobertura/coverage.xml
- ./cc-test-reporter upload-coverage
